apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-kafka-client
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
       name: python-client
        image: python:3.9-slim
       
        command: ["/bin/sh", "-c", "pip install confluent-kafka pandas && sleep infinity"]
        env:
         name: BOOTSTRAP_SERVERS
          value: "kafka.confluent.svc.cluster.local:9092"
         name: SCHEMA_REGISTRY_URL
          value: "http://schemaregistry.confluent.svc.cluster.local:8081"
         name: KAFKA_USER
          value: "admin-user"
         name: KAFKA_PASS
          value: "admin-password"